### ISSUE TITLE
Several marker problems/differences in 2.1.0 (compared to 1.5.1)

### ISSUE THREAD

**Issue by jypeter** [CDAT/cdat#1079] opened 2015-02-25 15:28 UTC
I have used test script listed at the end of this issue to test markers in 2.1.0 and see how they differ from 1.5.1. I have found several problems and differences, but @chaosphere2112 can probably use this script in the gallery once the problems are solved

I originally wanted to experiment with projections to see if #672 had been solved but I have found other problems and probably won't have time to experiment with non default projection. **My ultimate goal and need is of course to be able to overlay data points markers over a vcs map, whatever the projection is!**

 png created with 2.1.0
![test_simple_marker-2 1 0](https://cloud.githubusercontent.com/assets/2785573/6372426/69c2ca5c-bd04-11e4-96a7-3b567df63486.png)

png created with 1.5.1
![test_simple_marker-1 5 1](https://cloud.githubusercontent.com/assets/2785573/6372430/7ac27fbe-bd04-11e4-8e94-940d7f54c86a.png)

The problems and differences:
- The markers are smaller in 2.1.0 and 1.5.1 . You probably want to **check the scale to make sure to get the same size**, but _being able to get smaller markers than 1.5.1 is a good thing!_ So I hope we can use non integer marker sizes to be able to get lots of different marker sizes
- At least **one marker from 1.5.1 is missing from 2.1.0** and I get the following warning. You can also see the result on the plots above

```
/home/share/unix_files/cdat/versions/cdat_install_uv-2.1.0_x86_64_gcc4_13/lib/python2.7/site-packages/vcs/vcs2vtk.py:1113: UserWarning: unknown marker type: star, using dot
  warnings.warn("unknown marker type: %s, using dot" % t)
```
- **Non filled markers in 1.5.1 are filled in 2.1.0**! See the plots above: eg _triangle_up_ is the same as _triangle_up_fill_
- There is a _nice improvement_ I should mention! **The markers are much nicer in the 2.1.0 pdf than in 1.5.1**! But there is room for improvement. As you can see in the 300% magnified pdf screenshot below, with 1.5.1 on the left and 2.1.0 on the right, the _dot_ and _circle_ markers are much nicer in 2.1.0, but they should be described/rendered with a circle primitive (filled or empty) rather than with a list of segments
  ![magnified_pdf_vcs_markers](https://cloud.githubusercontent.com/assets/2785573/6372998/14f8cdec-bd08-11e4-9a89-90939fca6ece.jpg)
- When you look at the magnified pdf above, you see that the markers and text that have the same y coordinate have their **center vertically aligned in 1.5.1, but not in 2.1.0**. The vertical alignment seems better in the png files, but it's harder to tell. You would have to generate a higher resolution png

The test script:

```
#!/usr/bin/env python

# A simple vcs markers test/demo
#
# J-Y Peterschmitt - LSCE - 02/2015

import numpy as np, vcs

x = vcs.init()

# Create a first group of markers: a vertical line of 3 green
# triangles, a diagonal of orange diamonds and a diagonal of black
# disks
#
# Everything will be plotted in the 0.05 to 0.95 part of the canvas
# horizontally, and from 0.1 to 0.9 vertically (aka, the "viewport")
#
# The coordinates of the markers inside the viewport will be from 0 to
#100 (aka the "world coordinates")
marker_test = x.createmarker('marker_test')
marker_test.worldcoordinate = [0, 100, 0, 100]
marker_test.viewport = [0.05, 0.95, 0.1, 0.9]
marker_test.x = [[90, 90, 90],
                 [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100],
                 [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100]]
marker_test.y = [[25, 50, 75],
                 [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100],
                 [100, 90, 80, 70, 60, 50, 40, 30, 20, 10, 0]]
marker_test.type = ['triangle_down_fill',
                    'diamond_fill',
                    'dot']
marker_test.size = [20.,
                    20.,
                    15.]
marker_test.color = [243, # Green
                     248, # Orange
                     241] # Black

# Create a second group of markers, all red and of the same size,
# using the same viewport and world coordinates as marker_test
some_markers = ['dot', 'plus', 'star', 'circle', 'cross',
                'diamond', 'triangle_up', 'triangle_down',
                'triangle_down', 'triangle_left', 'triangle_right',
                'square', 'diamond_fill', 'triangle_up_fill',
                'triangle_down_fill', 'triangle_left_fill',
                'triangle_right_fill', 'square_fill']

x_mrk = 5
x_mrk_step = 40
y_mrk0 = 95
y_mrk = y_mrk0
y_mrk_step = 10
x_list = []
y_list = []
x_list_text = []
y_list_text = []
for mrk in some_markers:
    x_list.append([x_mrk])
    x_list_text.append(x_mrk + 5)
    y_list.append([y_mrk])
    y_list_text.append(y_mrk)

    # Determine the location of the next marker
    y_mrk -= y_mrk_step # y_list = y_list - y_mrk_step
    if y_mrk < 15:
        # Start a new column!
        x_mrk += x_mrk_step
        y_mrk = y_mrk0

marker_demo = x.createmarker('marker_demo')
marker_demo.worldcoordinate = marker_test.worldcoordinate
marker_demo.viewport = marker_test.viewport
marker_demo.x = x_list
marker_demo.y = y_list
marker_demo.type = some_markers
nb_markers = len(some_markers)
marker_demo.size = nb_markers * [15] # All the markers are of size 15
marker_demo.color = nb_markers * [242] # All the markers are red

# Plot the marker names next to the markers, using the same viewport
# and world coordinates as marker_demo (and marker_test)
marker_names = x.createtext('marker_names')
marker_names.worldcoordinate = marker_test.worldcoordinate
marker_names.viewport = marker_test.viewport
marker_names.x = x_list_text
marker_names.y = y_list_text
marker_names.string = some_markers
marker_names.color = 241

# Plot everything
x.plot(marker_test)
x.plot(marker_demo)
x.plot(marker_names)

# Save the plot to a png file
x.png('test_simple_marker', draw_white_background=True)
x.pdf('test_simple_marker')

# The end
```

**Comment by durack1** [comment] 2015-02-25 16:02
@jypeter @chaosphere2112 @doutriaux1 @dlonie this would appear to be related to #503 - @jypeter if you think these defaults are non-standard I agree with you that changing VCS to conform to expected conventions (angle signs, CCW etc) is a good idea.

**Comment by dlonie** [comment] 2015-02-25 16:20
Thanks for the awesome script that thoroughly exercises this functionality -- this definitely should go into our test suite when we address this issue.

Some perspective from the VTK side of things:

*Sizes* @doutriaux1 set the final scaling factors for these points in the vtk/vcs layer. Can you double check that these match what the vcs units are expected to be?

*Missing/incorrect markers* Several of these are explicitly generated polygons in the vcs layer. Should be easy to fix.

* Smooth edges in PDF* I don't think we can do much about this. The PDFs generated by GL2PS (the conversion library used by VTK) read vertex / line / polygon information from OpenGL and convert it into vector primitives. Since OpenGL doesn't support the concept of a "smooth" curve (everything must be sampled into a set of discrete lines), there's not a way to tell GL2PS to produce a smooth circle. Best we could do is crank up the resolution of the curve sampling.

*Vertical alignment* Vertical alignment of text is in flux in VTK at the moment. I'm slowly plugging away at improving the text capabilities as funding allows, but addressing the vertical alignment isn't something that's gotten much attention. One of my plans for VTK will improve this -- basically we need an explicit option to align to a "tight" bounding box of only the rendered text, instead of making assumptions about whether or not ascenders/descenders are fully utilized in a given text string.

**Comment by jypeter** [comment] 2015-02-25 16:49
@dlonie we need smooth edges in all the *raster output  types*, even at low resolution, and near perfect edges in *vector output types*, so it would be nice if *whatever can be done by subsampling or else* is done behind the scene without the user having to think about it. Of course, we don't want to get a giant pdf either...

For instance, in the case of the top 2 *surface air temperature* plot of #1080, I had to play with the width/height parameters of x.png in order to force a good sampling of the primitives. Otherwise I got ugly approximations of the primitives and weird squiggly meridians! That's why the png is so huge. I wish I could have gotten directly nice shapes at low resolution

**Comment by doutriaux1** [comment] 2015-02-25 17:39
@dlonie on the "smooth" thing. I think I remember VTK can define the number of points use for the glyph, let's try to play with this. (default is 6 I believe)

**Comment by doutriaux1** [comment] 2015-08-31 18:42
@sankhesh @jypeter is it a duplicate of #1439

**Comment by chaosphere2112** [comment] 2015-08-31 20:11
@jypeter I added star back into VCS around 2.2, I think, so that part is addressed.

**Comment by jypeter** [comment] 2015-09-01 08:49
@chaosphere2112 don't forget to add the script (or a variarion) to the gallery, if it works, now that the gallery is back.

The example should probably be placed next to http://uv-cdat.llnl.gov/examples/test_markers.html

**Closed** 2019-04-18 16:20 UTC
Labels: VCS
